/* emount_packets.h -- GENERATED by rebuild/tools/gen_packets.py, do not edit.
 * Source: ../fw/EA9-VER-1-8-0.bin, .data initialiser at flash 0x099d4, 1272 bytes.
 */
#ifndef EMOUNT_PACKETS_H
#define EMOUNT_PACKETS_H

#include <stdint.h>

#define EA9_DATA_LEN 1272
#define EA9_PACKET_COUNT 20

struct ea9_packet {
	uint8_t  id;
	uint16_t offset;   /* into ea9_data */
	uint16_t len;
};

/* Live, writable: the init handlers for ids 0x1b and 0x34 edit their frame
 * before sending it, and the status frames are rewritten every body frame. */
extern uint8_t ea9_data[EA9_DATA_LEN];
extern const struct ea9_packet ea9_packets[EA9_PACKET_COUNT];

#define EA9_OFF_01 0x038u
#define EA9_LEN_01 41u
#define EA9_OFF_05 0x1a8u
#define EA9_LEN_05 105u
#define EA9_OFF_06 0x000u
#define EA9_LEN_06 48u
#define EA9_OFF_07 0x064u
#define EA9_LEN_07 43u
#define EA9_OFF_08 0x0b4u
#define EA9_LEN_08 210u
#define EA9_OFF_09 0x188u
#define EA9_LEN_09 20u
#define EA9_OFF_0A 0x334u
#define EA9_LEN_0A 25u
#define EA9_OFF_0B 0x09cu
#define EA9_LEN_0B 11u
#define EA9_OFF_0C 0x090u
#define EA9_LEN_0C 10u
#define EA9_OFF_0D 0x0a8u
#define EA9_LEN_0D 10u
#define EA9_OFF_10 0x19cu
#define EA9_LEN_10 10u
#define EA9_OFF_19 0x328u
#define EA9_LEN_19 10u
#define EA9_OFF_1B 0x350u
#define EA9_LEN_1B 19u
#define EA9_OFF_28 0x364u
#define EA9_LEN_28 44u
#define EA9_OFF_32 0x214u
#define EA9_LEN_32 16u
#define EA9_OFF_34 0x308u
#define EA9_LEN_34 32u
#define EA9_OFF_3D 0x280u
#define EA9_LEN_3D 72u
#define EA9_OFF_3F 0x234u
#define EA9_LEN_3F 74u
#define EA9_OFF_4C 0x224u
#define EA9_LEN_4C 16u
#define EA9_OFF_5A 0x2c8u
#define EA9_LEN_5A 64u

/* Frame edits the stock handlers make before sending.  Three handlers do this
 * and none of them is optional -- see decode_handlers() in the generator for
 * what happened when they were dropped.  EA9_FIXUP_RX means the byte is copied
 * from the received frame at that offset. */
#define EA9_FIXUP_IMM 0
#define EA9_FIXUP_RX  1
#define EA9_FIXUP_COUNT 8

struct ea9_fixup {
	uint8_t id;
	uint8_t off;      /* into the outgoing frame */
	uint8_t kind;     /* EA9_FIXUP_IMM or EA9_FIXUP_RX */
	uint8_t val;      /* the constant, or the offset into the received frame */
};

extern const struct ea9_fixup ea9_fixups[EA9_FIXUP_COUNT];

#endif /* EMOUNT_PACKETS_H */
